name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - run: go install github.com/a-h/templ/cmd/templ@latest

      - run: npm install
      - run: npx @tailwindcss/cli -i static/input.css -o static/output.css --minify

      - run: templ generate

      - run: go test -v -count=1 ./...
